#!/bin/sh

# cd into the directory of the script
cd "$(dirname "$0")"

if ! [ -d ~/.dotfiles_backup ]; then mkdir ~/.dotfiles_backup; fi
for file in ./*; do
  if [ -f $file -a $file != './create_symlinks' -a $file != './README.md' ]; then
    basefile="$(basename $file)"
    echo "$basefile"
    if [ -f ~/.$basefile -a ! -L ~/.$basefile ]; then 
        mv ~/.$basefile ~/.dotfiles_backup/$basefile; 
    fi
    ln -sf $(readlink -f ./$basefile) ~/.$basefile 
  fi
done
