#!/bin/sh

# cd into the directory of the script
cd "$(dirname "$0")"

if ! [ -d ~/.dotfiles_backup ]; then mkdir ~/.dotfiles_backup; fi
for file in bashrc condarc gitconfig profile vimrc
do
    echo "$file"
    if [ -f ~/.$file -a ! -L ~/.$file ]; then 
        mv ~/.$file ~/.dotfiles_backup/$file; 
    fi
    ln -sf $(realpath ./$file) ~/.$file 
done
